---
title: "Teste"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dtwSat)
library(caret)
```

```{r imagens_2013-2018}
blue <- brick(list("IMAGENS\\2013.B2.tif", "IMAGENS\\2014.B2.tif", 
                   "IMAGENS\\2015.B2.tif", "IMAGENS\\2016.B2.tif", 
                   "IMAGENS\\2017.B2.tif", "IMAGENS\\2018.B2.tif"))
green <- brick(list("IMAGENS\\2013.B3.tif", "IMAGENS\\2014.B3.tif", 
                    "IMAGENS\\2015.B3.tif", "IMAGENS\\2016.B3.tif", 
                    "IMAGENS\\2017.B3.tif", "IMAGENS\\2018.B3.tif"))
red <- brick(list("IMAGENS\\2013.B4.tif", "IMAGENS\\2014.B4.tif", 
                  "IMAGENS\\2015.B4.tif", "IMAGENS\\2016.B4.tif", 
                  "IMAGENS\\2017.B4.tif", "IMAGENS\\2018.B4.tif"))
```


```{r}
timeline <- as.Date(c("2013-01-01", "2014-01-01", "2015-01-01", "2016-01-01", 
                      "2017-01-01", "2018-01-01"))
```


```{r}
rts <- twdtwRaster(blue, green,  red, timeline = timeline)
```


```{r}
# Location and time range 
ts_location <- data.frame(longitude = -52.391637, latitude = -26.871172, 
                         from = "2013-01-01", to = "2018-01-01")
prj_string <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
ts <- getTimeSeries(rts, y = ts_location, proj4string = prj_string)
```


```{r}
plot(ts, type = "timeseries")
```

```{r}
field_samples <- read.csv("samples.csv")
proj_str <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
```

```{r}
set.seed(1)
I <- unlist(createDataPartition(field_samples$label, p = 0.1))
training_samples <- field_samples[I, ]
validation_samples <- field_samples[-I, ]
```

```{r}
training_ts <- getTimeSeries(rts, y = training_samples, proj4string = proj_str)
validation_ts <- getTimeSeries(rts, y = validation_samples, proj4string = proj_str)
```

```{r , echo = TRUE, eval = TRUE}
temporal_patterns <- createPatterns(training_ts, freq = 8, formula = y ~ s(x))
```

